services:

  web:
    build:
      context: .
      dockerfile: src/web/Dockerfile

    ports:
      - "80:80"

    restart: unless-stopped

  backend:

    build:
      context: .
      dockerfile: src/backend/Dockerfile

    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    volumes:

      # DuckDB
      - ./database:/app/database

      # Modelo IA
      - ./models:/app/models

      # SQLite de Django
      - ./src/backend/db.sqlite3:/app/src/backend/db.sqlite3

    restart: unless-stopped

  frontend:

    build:
      context: .

      dockerfile: src/frontend/Dockerfile

    env_file:
      - .env.docker

    ports:
      - "8501:8501"

    depends_on:
      - backend

    restart: unless-stopped